|  Column name  |  Description  |
| ----- | ------- |
| Num_posts        | Number of total posts that the user has ever posted   |
| Num_following    | Number of following                                   |
| Num_followers    | Number of followers                                   |
| Biography_length | Length (number of characters) of the user's biography |
| Picture_availability | Value 0 if the user has no profile picture, or 1 if has |
| Link_availability| Value 0 if the user has no external URL, or 1 if has |
| Average_caption_length | The average number of character of captions in media |
| Caption_zero     | Percentage (0.0 to 1.0) of captions that has almost zero (<=3) length |
| Non_image_percentage | Percentage (0.0 to 1.0) of non-image media. There are three types of media on an Instagram post, i.e. image, video, carousel
| Engagement_rate_like | Engagement rate (ER) is commonly defined as (num likes) divide by (num media) divide by (num followers)
| Engagement_rate_comment | Similar to ER like, but it is for comments |
| Location_tag_percentage | Percentage (0.0 to 1.0) of posts tagged with location |
| Average_hashtag_count   | Average number of hashtags used in a post |
| Promotional_keywords | Average use of promotional keywords in hashtag, i.e. regrann, contest, repost, giveaway, mention, share, give away, quiz |
| Followers_keywords | Average use of followers hunter keywords in hashtag, i.e. follow, like, folback, follback, f4f|
| Cosine_similarity  | Average cosine similarity of between all pair of two posts a user has |
| Post_interval      | Average interval between posts (in hours) |
| real_fake          | r (real/authentic user), f (fake user/bought followers) |

# Q1: Import labraries

In [1]:
import numpy as np
import pandas as pd

# Q2: Read instagram_users.csv file

In [2]:
df = pd.read_csv("instagram_users.csv")

In [3]:
df.head()

Num_posts  Num_following  Num_followers  Biography_length  \
0          44             48            325                33   
1          10             66            321               150   
2          33            970            308               101   
3          70             86            360                14   
4           3             21            285                73   

   Picture_availability  Link_availability  Average_caption_length  \
0                     1                  0                      12   
1                     1                  0                     213   
2                     1                  1                     436   
3                     1                  0                       0   
4                     1                  0                      93   

   Caption_zero  Non_image_percentage  Engagement_rate_like  \
0           0.0                   0.0                  0.00   
1           0.0                   1.0                 14.39   
2           0.0                   1.0                 10.10   
3           1.0                   0.0                  0.78   
4           0.0                   0.0                 14.29   

   Engagement_rate_comment  Location_tag_percentage  Average_hashtag_count  \
0                     0.00                    0.000                    0.0   
1                     1.97                    0.000                    1.5   
2                     0.30                    0.000                    2.5   
3                     0.06                    0.000                    0.0   
4                     0.00                    0.667                    0.0   

   Promotional_keywords  Followers_keywords  Cosine_similarity  Post_interval  \
0                   0.0               0.000           0.111111       0.094985   
1                   0.0               0.000           0.206826     230.412857   
2                   0.0               0.056           0.572174      43.569939   
3                   0.0               0.000           1.000000       5.859799   
4                   0.0               0.000           0.300494       0.126019   

  real_fake  
0      fake  
1      fake  
2      fake  
3      fake  
4      fake

# Q3: Split tha dataset into training and testing

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X, y = df.iloc[:, :-1], df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

# Q4: Build three machine models 

## Q4.1: The first machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

### Decision Tree Classifier

In [6]:
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as mm

#### Training and prediction

In [7]:
print("Decision Trees")
DT_model = DecisionTreeClassifier().fit(X_train, y_train)

Decision Trees


In [8]:
DT_pred = DT_model.predict(X_test)

#### Accuracy

In [9]:
mm.accuracy_score(y_test, DT_pred)

0.8543115077306216

In [10]:
mm.confusion_matrix(y_test, DT_pred)

array([[8161, 1314],
       [1494, 8305]])

## Q4.2: The second machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

### Random Forest Classifier

In [11]:
from sklearn.ensemble import RandomForestClassifier
import sklearn.metrics as mm

#### Training and prediction

In [12]:
print("Random Forest")
RF_model = RandomForestClassifier(n_estimators = 50).fit(X_train, y_train)

Random Forest


In [13]:
RF_pred = RF_model.predict(X_test)

#### Accuracy

In [14]:
mm.accuracy_score(y_test, RF_pred)

0.8934834492061845

In [15]:
mm.confusion_matrix(y_test, RF_pred)

array([[7954, 1521],
       [ 532, 9267]])

## Q4.3: The third machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

### Adaboost Classifier

In [16]:
from sklearn.ensemble import AdaBoostClassifier
import sklearn.metrics as mm

#### Training and prediction

In [17]:
print("Adaboost Classifier")
AB_model = AdaBoostClassifier(n_estimators = 50).fit(X_train, y_train)

Adaboost Classifier


In [18]:
AB_pred = AB_model.predict(X_test)

#### Accuracy

In [19]:
mm.accuracy_score(y_test, AB_pred)

0.8641174639410605

In [20]:
mm.confusion_matrix(y_test, AB_pred)

array([[8136, 1339],
       [1280, 8519]])